### Question 1: Write a function that takes two sets as input and returns their union.
- `Sample Input: set1 = {1, 2, 3}, set2 = {3, 4, 5}`
- `Sample Output: {1, 2, 3, 4, 5}`

In [ ]:
# Please write The solution Here for above question 1:
a={1,2,3}
b={3,4,5}
print(a.union(b))

{1, 2, 3, 4, 5}

### Question 2: Write a function that takes two sets as input and returns their intersection.

   - `Sample Input: set1 = {1, 2, 3}, set2 = {3, 4, 5}`
   - `Sample Output: {3}`

In [ ]:
# Please write The solution Here for above question 2:
a={1,2,3}
b={3,4,5}
print(a.intersection(b))

{3}

### Question 3:  Write a function that takes two sets as input and returns the elements that are in the first set but not in the second set.
- `Sample Input: set1 = {1, 2, 3}, set2 = {3, 4, 5}`
- `Sample Output: {1, 2}`

In [ ]:
# Please write The solution Here for above question 3:
set1={1,2,3}
set2={3,4,5}
print(set1-set2)

{1, 2}

### Question 4: Write a function that checks if one set is a subset of another set.
   - `Sample Input: set1 = {1, 2, 3}, set2 = {1, 2, 3, 4, 5}`
   - `Sample Output: True`

In [13]:
# Please write The solution Here for above questi
# python isjoint()#if they have common element
set1={1,2,3}
set2={1,2,3,4,5}
print(set1 is_subset of(set2))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-13-84d6bb0ea3fe>, line 5)

### Question 5: Write a function that returns the symmetric difference between two sets.

   - `Sample Input: set1 = {1, 2, 3, 4}, set2 = {3, 4, 5, 6}`
   - `Sample Output: {1, 2, 5, 6}`

In [ ]:
# Please write The solution Here for above question 5:
set1={1,2,3,4}
set2={3,4,5,6}
print(set1.symmetric_difference(set2))

{1, 2, 5, 6}

### Question 6:  Write a function that takes a universal set and a subset as input and returns the complement of the subset.

   - `Sample Input: universal_set = {1, 2, 3, 4, 5}, subset = {3, 4}`
   - `Sample Output: {1, 2, 5}`

In [ ]:
# Please write The solution Here for above question 6:
a={1,2,3,4,5}
b={3,4}
c=a-b
print(c)

{1, 2, 5}

### Question 7 : Write a function that returns the number of elements in a set.

   - `Sample Input: my_set = {10, 20, 30, 40, 50}`
   - `Sample Output: 5`

In [ ]:
# Please write The solution Here for above question 7:
a={10,20,30,40,50}
print(len(a))

5

### Question 8 : Write a function that returns the sum of all elements in a set of numbers.

   - `Sample Input: num_set = {2, 4, 6, 8, 10}`
   - `Sample Output: 30`

In [ ]:
# Please write The solution Here for above question 8:
a={2,4,6,8,10}
b=sum(a)
print(b)

30


### Question 9 : Write a function that returns the size of the intersection between two sets.

   - `Sample Input: set1 = {1, 2, 3, 4}, set2 = {3, 4, 5, 6}`
   - `Sample Output: 2`

In [7]:
# Please write The solution Here for above question 9:
set1={1,2,3,4}
set2={3,4,5,6}
def intersection_size(set1,set2):
   intersection_set=set1.intersection(set2)
   return len (intersection_set)
print(intersection_size(set1,set2))

2

### Question 10:Write a function that generates the powerset of a given set (all possible subsets).

- `Sample Input: my_set = {1, 2}`
- `Sample Output: {{}, {1}, {2}, {1, 2}}`

In [ ]:
# Please write The solution Here for above questio